name: geog0111
channels:
  - defaults
dependencies:
  - matplotlib-base
  - python[version='>=3.7']
  - shapely
  - pycodestyle
  - libnetcdf
  - fsspec
  - autopep8
  - ipympl
  - fiona
  - pandocfilters
  - scikit-learn
  - statsmodels
  - geopandas
  - beautifulsoup4
  - pandas
  - cartopy
  - seaborn
  - pytest
  - ipython
  - hdf5
  - nodejs
  - gdal
  - numpydoc
  - ipykernel
  - jupyter_console
  - sphinx
  - pandoc
  - git
  - jupyterlab
  - nbconvert
  - flake8
  - xarray
  - matplotlib
  - scipy
  - tensorflow
  - rasterio
  - netcdf4
  - pip
  - libgdal
  - black
  - ipywidgets
  - scikit-image
  - numpy
  - astropy
  - jupyter
  - yapf
  - xlrd