name: geog0121
channels:
  - conda-forge
dependencies:
  - python=3.6
  # core scipy packages
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray
  - dask
  # jupyter-related
  - nbserverproxy
  - jupyter
  - jupyterlab
  - jupyterhub
  - ipywidgets
  - ipyleaflet
  - bash_kernel
  - ipykernel
  - nb_conda
  - nb_conda_kernels
  # geospatial
  - cartopy
  - geopandas
  - netcdf4
  # geoscience-related
  - climlab
  - xesmf
  # zarr-related
  - zarr
  # xarray-related
  - xgcm
